api/urls.py
from django.urls import include, path, re_path

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from api import views

router = routers.DefaultRouter()
router.register(r'animals', views.AnimalViewSet)
router.register(r'persons', views.PersonViewSet)
router.register(r'adopter-family', views.AdopterFamilyViewSet)
router.register(r'fosters', views.FosterViewSet)


urlpatterns = [
    path('', include((router.urls, 'api'), namespace='api')),
    re_path(r'^api-auth/', include('rest_framework.urls',
                                   namespace='rest_framework')),
    re_path(r'^api-token-auth/', obtain_auth_token),
]

webapp/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('mascotas/', views.AnimalsView.as_view(), name='animals'),
    path('preguntas-frequentes', views.FrequentQuestionsView.as_view(),
         name='frequentQuestions'),
    path('ayuda', views.HelpView.as_view(), name='help'),
    path('contacto', views.ContactView.as_view(), name='contact'),
    re_path(r'^mascota/(?P<slug>[\w-]+)/$', views.AnimalDetail.as_view(),
            name='animal_detail'),
]

core/models.py
import os

from django.conf import settings
from django.db import models
from django.urls import reverse

from autoslug import AutoSlugField
from versatileimagefield.fields import VersatileImageField
from versatileimagefield.placeholder import OnDiscPlaceholderImage

from core.services import generate_unique_file_path

NO_IMAGE_PLACEHOLDER = OnDiscPlaceholderImage(
    path=os.path.join(settings.PROJECT_DIR,
                      'static',
                      'img',
                      'no-image-placeholder.png'),
)


class TimeStampleModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        abstract = True


class Animal(TimeStampleModel):
    ANIMAL_TYPE_CHOICES = (
        ('DOG', 'Perro'),
        ('CAT', 'Gato'),
    )
    SEX_CHOICES = (
        ('MALE', 'Macho'),
        ('FEMALE', 'Hembra'),
    )
    STATE_CHOICES = (
        ('AVAILABLE', 'Disponible'),
        ('UNAVAILABLE', 'No Disponible'),
        ('URGENCY', 'Urgente')
    )
    SIZE_CHOICES = (
        ('BIG', 'Grande'),
        ('MEDIUM', 'Mediano'),
        ('LITTLE', 'Pequeño'),
    )
    name = models.CharField('Nombre', max_length=50)
    birth_date = models.DateField('Fecha de nacimiento')
    entry_date = models.DateField('Fecha de entrada')
    departure_date = models.DateField(
        'Fecha de salida',
        blank=True,
        null=True
        )
    description = models.TextField(
        'Descripcion',
        blank=True,
        null=True
        )
    image = VersatileImageField(
        'Imagen',
        null=True,
        blank=True,
        upload_to=generate_unique_file_path,
        placeholder_image=NO_IMAGE_PLACEHOLDER
        )
    size = models.CharField(
        'Tamaño',
        max_length=50,
        choices=SIZE_CHOICES, default='MEDIUM'
        )
    animal_type = models.CharField(
        'Tipo',
        max_length=50,
        choices=ANIMAL_TYPE_CHOICES,
        default='DOG'
        )
    sex = models.CharField(
        'Sexo',
        max_length=50,
        choices=SEX_CHOICES,
        default='MALE'
        )
    state = models.CharField(
        'Estado',
        max_length=50,
        choices=STATE_CHOICES,
        default='UNAVAILABLE'
        )
    slug = AutoSlugField(populate_from='name', unique=True)

    def __str__(self):
        return f'{self.name} {self.animal_type}'

    def get_absolute_url(self):
        return reverse('animal_detail', args=[self.slug])

    class Meta:
        verbose_name = 'Mascota'
        verbose_name_plural = 'Mascotas'


class Person(TimeStampleModel):
    name = models.CharField('Nombre', max_length=50)
    last_name = models.CharField('Apellidos', max_length=70)
    phone = models.CharField('Telefono', max_length=20)
    address = models.CharField('Direccion', max_length=100)
    email = models.EmailField('Email', max_length=100, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'


class Foster(TimeStampleModel):
    animal = models.ForeignKey('Animal', on_delete=models.CASCADE)
    person = models.ForeignKey('Person', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Acogida'
        verbose_name_plural = 'Acogidas'


class AdopterFamily(TimeStampleModel):
    animal = models.ForeignKey('Animal', on_delete=models.CASCADE)
    person = models.ForeignKey('Person', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.animal.state = 'UNAVAILABLE'
        self.animal.save()

    class Meta:
        verbose_name = 'Adopcion'
        verbose_name_plural = 'Adopciones'

webapp/views.py
import random
from datetime import datetime as dt

from django.contrib import messages
from django.db.models import BooleanField, Case, F, When
from django.db.models.functions import Extract
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import DetailView, TemplateView

from django_filters.views import FilterView

from core import filters, forms
from core.models import Animal
from webapp import quotes


class HomeView(FilterView):
    model = Animal
    template_name = 'webapp/home.html'
    filterset_class = filters.AnimalFilter

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context.update({
            'quote': (random.choice(list(quotes.quotes.items()))),
            'animals': (Animal.objects.filter(state='URGENCY')
                        .order_by('-state', 'entry_date')),
        })
        return context


class AnimalsView(FilterView):
    model = Animal
    template_name = 'webapp/animals.html'
    paginate_by = 9
    filterset_class = filters.AnimalFilter
    context_object_name = 'animals'

    def get_queryset(self):
        return (Animal.objects
                .annotate(duration=Extract(dt.now() - F('birth_date'), 'days'))
                .annotate(is_puppy=Case(When(duration__lt=365, then=True),
                          default=False, output_field=BooleanField()))
                .exclude(state='UNAVAILABLE')
                .order_by('-state', 'entry_date'))

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(*args, **kwargs)
        aux = self.request.GET.copy()
        if aux.get('page'):
            aux.pop('page')
        data['query_get_string'] = aux.urlencode()
        return data


class FrequentQuestionsView(TemplateView):
    template_name = 'webapp/frequent_questions.html'


class HelpView(TemplateView):
    template_name = 'webapp/help.html'


class ContactView(generic.FormView):
    template_name = 'webapp/contact.html'
    form_class = forms.ContactForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,
                         'Gracias por contactar con nosotros!')
        return super(ContactView, self).form_valid(form)

    def form_invalid(self, *args, **kwargs):
        messages.error(self.request, 'Error enviando el formulario')
        return super().form_invalid(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('home')


class AnimalDetail(DetailView, generic.FormView):
    model = Animal
    template_name = 'webapp/animal_detail.html'
    form_class = forms.ContactForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request,
                         'Gracias por contactar con nosotros!')
        return super(AnimalDetail, self).form_valid(form)

    def form_invalid(self, *args, **kwargs):
        messages.error(self.request, 'Error enviando el formulario')
        return super().form_invalid(*args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('home')

    def get_queryset(self):
        return Animal.objects.exclude(state='UNAVAILABLE')

webapp/templates/webapp/_footer.html
<footer class="footer">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <p class="logo foot">Animal Shelter</p>
                The source code is licensed
                <a href="https://opensource.org/licenses/Apache-2.0">Apache-2.0</a>.
                <br>
                <a href="https://github.com/arponpes/Animal-Shelter" class="is-disabled foot-icon">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <div class="column is-half">
                <strong>Animal Shelter</strong> by
                <label> Aaron Dominguez Diez</label>
                <label>
                    <i class="far fa-copyright"></i> 2018</label>
                <a href="https://github.com/arponpes" class="is-disabled foot-icon">
                    <i class="fab fa-github"></i>
                </a>
                <a href="https://www.linkedin.com/in/aar%C3%B3n-dom%C3%ADnguez-d%C3%ADez-862692136/" class="foot-icon">
                    <i class="fab fa-linkedin-in"></i>
                </a>.
            </div>
        </div>
    </div>
</footer>

webapp/templates/webapp/_message.html
{% if messages %}
{% for message in messages %}
<div class="modal">
        <div class="modal-background"></div>
        <div class="modal-card">
          <header class="modal-card-head">
            <p class="modal-card-title">Informacion</p>
            <button class="delete" aria-label="close"></button>
          </header>
          <section class="modal-card-body">
                <p{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
          </section>
        </div>
      </div>
{% endfor %} {% endif %}

webapp/templates/webapp/_navbar.html
{% url 'home' as home_url %}
{% url 'animals' as animals_url %}
{% url 'frequentQuestions' as frequentQuestions_url %}
{% url 'help' as help_url %}
{% url 'contact' as contact_url %}
<nav class="navbar is-light is-fixed-top">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'home' %}">
        <p class="logo-font">Animal Shelter</p>
      </a>
      <div class="navbar-burger burger" data-target="navbar_content">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <div class="navbar-menu" id="navbar_content">
      <div class="navbar-start">
        <a class="navbar-item {% if request.get_full_path == home_url %}is-active{% endif %}" id="home" href="{% url 'home' %}">Inicio</a>
        <a class="navbar-item {% if request.get_full_path == animals_url %}is-active{% endif %}" id="animals" href="{% url 'animals' %}">Animales</a>
        <a class="navbar-item {% if request.get_full_path == frequentQuestions_url %}is-active{% endif %}" id="frequentQuestions" href="{% url 'frequentQuestions' %}">Preguntas Frecuentes</a>
        <a class="navbar-item {% if request.get_full_path == help_url %}is-active{% endif %}" id="help" href="{% url 'help' %}">Ayudanos</a>
        <a class="navbar-item {% if request.get_full_path == contact_url %}is-active{% endif %}" id="contact" href="{% url 'contact' %}">Contacto</a>
      </div>
      <div class="navbar-end">
          
        <a class="navbar-item fa-2x" href="https://www.facebook.com/"><i class="fab fa-facebook-square"></i></a>
        <a class="navbar-item fa-2x" href="https://www.instagram.com/?hl=es"><i class="fab fa-instagram "></i></a>
      </div>
    </div>
  </div>
</nav>

webapp/templates/webapp/_pagination.html
<div class="margin-top-less">
  <nav class="pagination" role="navigation" aria-label="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a class="button" href="?page={{ 1 }}&{{query_get_string}}">
        <i class="fas fa-angle-double-left"></i>
      </a>
      <a class="button" href="?page={{ page_obj.previous_page_number }}&{{query_get_string}}">
        <i class="fas fa-angle-left"></i>
      </a>
      {% else %}
      <a class="button" title="Disabled button" disabled>
        <i class="fas fa-angle-double-left"></i>
      </a>
      <a class="button" title="Disabled button" disabled>
        <i class="fas fa-chevron-left"></i>
      </a>
      {% endif %}
      <span class="button is-static">
        {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
      <a class="button" href="?page={{ page_obj.next_page_number }}&{{query_get_string}}">
        <i class="fas fa-angle-right"></i>
      </a>
      <a class="button" href="?page={{ page_obj.paginator.num_pages }}&{{query_get_string}}">
        <i class="fas fa-angle-double-right"></i>
      </a>
      {% else %}
      <a class="button" title="Disabled button" disabled>
        <i class="fas fa-angle-right"></i>
      </a>
      <a class="button" title="Disabled button" disabled>
        <i class="fas fa-angle-double-right"></i>
      </a>
      {% endif %}
    </span>
  </nav>
</div>

webapp/templates/webapp/animal_detail.html
{% extends 'webapp/base.html' %}
{% load static from staticfiles %}
{% load widget_tweaks %}
{% block content %}
{% include 'webapp/_navbar.html' %}
<section class="section margin-top">
    <div class="container">
        <h1 class="title">
            {{animal.name}} {% if animal.state == 'URGENCY' %}
            <span class="tag is-danger">{{animal.get_state_display}}</span>
            {% endif %}
        </h1>
        <div class="columns">
            <div class="column">
                <figure class="image">
                    <img src="{{ animal.image.url }}" />
                </figure>
            </div>
            <div class="column">
                <div class="content is-medium">
                    <h2 class="subtitle is-3">Datos</h2>
                    <div class="columns">
                        <div class="column is-half">
                            <p>
                                <strong> Fecha de nacimiento</strong>
                            </p>
                            <p>{{animal.birth_date}}</p>
                            <p>
                                <strong>Mascota</strong>
                            </p>
                            <p>
                                {{animal.get_animal_type_display}}
                            </p>
                            <p>
                                <strong>Tamaño</strong>
                            </p>
                            <p>
                                {{animal.get_size_display}}
                            </p>
                        </div>
                        <div class="column is-half">
                            <p>
                                <strong>Descripcion</strong>
                            </p>
                            <p>
                                {{animal.description}}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="content is-medium">
                <p class="subtitle center"><strong>Hablamos sobre {{animal.name}}?</strong></p>
                </div>
                <form method="post" id="contact-form" class="form" enctype="multipart/form-data">{% csrf_token %}
                    <div class="field {% if form.name.errors %}error{% endif %}">
                        <label class="label">Nombre</label>
                        {% render_field form.name|add_class:"input" placeholder='Nombre' %} {{ form.name.errors.0 }}
                    </div>
                    <div class="field {% if form.subject.errors %}error{% endif %}">
                        <label class="label">Asunto</label>
                        {% render_field form.subject|add_class:"input" placeholder='Asunto' value=animal.name %} {{ form.subject.errors.0 }}
                    </div>
                    <div class="field {% if form.email.errors %}error{% endif %}">
                        <label class="label">Email</label>
                        {% render_field form.email|add_class:"input" placeholder='Email' %} {{ form.email.errors.0 }}
                    </div>
                    <div class="field {% if form.message.errors %}error{% endif %}">
                        <label class="label">Mensaje</label>
                        {% render_field form.message|add_class:"textarea" placeholder='Mensaje' %} {{ form.message.errors.0 }}
                    </div>
                    <button class="button is-primary" id="btn-send" type="submit">Enviar</button>
                </form>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/protect_contact.js' %}"></script>
{% endblock content %}

webapp/templates/webapp/animals.html
{% extends 'webapp/base.html' %}
{% load static from staticfiles %}
{% block content %}
{% include 'webapp/_navbar.html' %}
<section class="section margin-top">
  <div class="container">
    <form action="" id="form" method="get">
      <h1 class="title center">
        Mascotas!
      </h1>
      <div class="box">
      <div class="contenedor">
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.animal_type name='animal_type' title='Animal' selected=request.GET.animal_type%}
          </div>
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.sex name='sex' title='Sexo' selected=request.GET.sex %}
          </div>
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.size name='size' title='Tamaño' selected=request.GET.size %}
          </div>
          <div class="item">
              {% include 'filter/_filter.html' with field=filter.form.fields.is_puppy name='is_puppy' title='Edad' selected=request.GET.is_puppy %}
          </div>
        </div>
      </div>        
    </form>
    <div class=" margin-top">
    <div class='columns is-multiline fixed-height'>
      {% for animal in animals %}
      <div class='column is-4-desktop is-half-tablet'>
          <a class="" href="{% url 'animal_detail' slug=animal.slug %}">
        <div class="card ">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="{{ animal.image.crop.470x350 }}" />
            </figure>
          </div>
          <div class="card-content">
            <div class="media-content">
              <a class="title is-4" href="{% url 'animal_detail' slug=animal.slug %}">
                {{animal.name}} {% if animal.state == 'URGENCY' %}
                <span class="tag is-danger">{{animal.get_state_display}}</span>
                {% endif %}
              </a>
            </div>
            <div class="content">
              <p>{{animal.description|truncatechars_html:175 }}</p>
            </div>
            <div class="columns is-mobile">
              <div class="column is-half card-down is-half-mobile">
                <Strong>
                  <label>Animal:</label>
                </Strong>
                {{animal.get_animal_type_display}}
                <br>
                <Strong>
                  <label>Sexo:</label>
                </Strong>
                {{animal.get_sex_display}}
                <br>
                <Strong>
                  <label>Tamaño:</label>
                </Strong>
                {{animal.get_size_display}}
                <br>
              </div>
              <div class="column is-half is-half-mobile">
                <strong>
                  <p>Fecha nacimiento</p>
                </strong>
                <time>{{animal.birth_date}}</time>
              </div>
            </div>
          </div>
        </div>
          </a>
      </div>
      {% endfor %}
    </div>
    </div>
    {% include 'webapp/_pagination.html' %}
</section>
<script src="{% static 'js/filters.js' %}"></script> {% endblock content %}

webapp/templates/webapp/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Animal Shelter</title>
    <link rel="apple-touch-icon" sizes="180x180" href="../../../rootfiles/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../../../rootfiles/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../../../rootfiles/favicon-16x16.png">
    <link rel="manifest" href="../../../rootfiles/site.webmanifest">
    <link rel="mask-icon" href="../../../rootfiles/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="../../../rootfiles/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="../../../../rootfiles/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <meta name="keywords" content="animal, mascota, adoptar, perro, gato, refugio">
    <meta name="description" content="Animal Shelter | Refugio de animales en el area de Pontevedra.">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.min.css">
    <link href="https://fonts.googleapis.com/css?family=Luckiest+Guy" rel="stylesheet"> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://momentjs.com/downloads/moment.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9"
    crossorigin="anonymous">
    <script src="{% static 'js/burger.js' %}"></script>
    <link rel="shortcut icon" type="image/png" href="img/favicon.ico"/>
</head>
<body>
    <div class="app">
        <main class="main">
    {% block content %}
    {% endblock %}
</main>
    {% include 'webapp/_footer.html' %}
    </div>
</body>
</html>

webapp/templates/webapp/contact.html
{% extends 'webapp/base.html' %}
{% load static from staticfiles %}
{% load widget_tweaks %}
{% block content %}
{% include 'webapp/_navbar.html' %}
<div class="container">
  <section class="section margin-top">
    <h1 class="title logo">
      ANIMAL SHELTER
    </h1>
    <div class="content is-medium">
      <p>La Protectora de animales
        <strong> Animal Shelter </strong> es una asociación sin ánimo de lucro fundada en 2018 con la
        <strong> finalidad primordial de la defensa y protección de los animales </strong> mediante la recogida de perros abandonados,
        promover su defensa mediante campañas de concienciación, divulgación, y la gestión de nuestro refugio. Nuestra actividad
        principal es el cuidado, a todos los niveles, de los animales que viven en nuestro refugio para conseguir que todos
        ellos se sientan queridos y seguros. Aquí vivirán hasta que consigan una familia que les
        <strong> adopte de forma responsable </strong> y les asegure un futuro feliz y una vida digna.
      </p>
    </div>
    <h2 class="title">Contacta con nosotros</h2>
    <div class="content is-medium">
      <p>Cualquier duda que tengas, so</strong>bre la adopcion, voluntariado, donaciones...</p>
    </div>
    <form method="post" id="contact-form" class="form" enctype="multipart/form-data">{% csrf_token %}
      <div class="field {% if form.name.errors %}error{% endif %}">
        <label class="label">Nombre</label>
        {% render_field form.name|add_class:"input" placeholder='Nombre' %} {{ form.name.errors.0 }}
      </div>
      <div class="field {% if form.subject.errors %}error{% endif %}">
        <label class="label">Asunto</label>
        {% render_field form.subject|add_class:"input" placeholder='Asunto' %} {{ form.subject.errors.0 }}
      </div>
      <div class="field {% if form.email.errors %}error{% endif %}">
        <label class="label">Email</label>
        {% render_field form.email|add_class:"input" placeholder='Email' %} {{ form.email.errors.0 }}
      </div>
      <div class="field {% if form.message.errors %}error{% endif %}">
        <label class="label">Mensaje</label>
        {% render_field form.message|add_class:"textarea" placeholder='Mensaje' %} {{ form.message.errors.0 }}
      </div>
      <button class="button is-primary" id="btn-send" type="submit">Enviar</button>
    </form>
  </section>
</div>
<script src="{% static 'js/protect_contact.js' %}"></script>
{% endblock content %}

webapp/templates/webapp/footer.html
<footer class="footer">
    <div class="container">
        <div class="columns">
            <div class="column is-half">
                <p class="logo foot">Animal Shelter</p>
                The source code is licensed
                <a href="https://opensource.org/licenses/Apache-2.0">Apache-2.0</a>.
                <br>
                <a href="https://github.com/arponpes/Animal-Shelter" class="is-disabled foot-icon">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <div class="column is-half">
                <strong>Animal Shelter</strong> by
                <label> Aaron Dominguez Diez</label>
                <label>
                    <i class="far fa-copyright"></i> 2018</label>
                <a href="https://github.com/arponpes" class="is-disabled foot-icon">
                    <i class="fab fa-github"></i>
                </a>
                <a href="https://www.linkedin.com/in/aar%C3%B3n-dom%C3%ADnguez-d%C3%ADez-862692136/" class="foot-icon">
                    <i class="fab fa-linkedin-in"></i>
                </a>.
            </div>
        </div>
    </div>
</footer>

webapp/templates/webapp/home.html
{% extends 'webapp/base.html' %}{% load static from staticfiles %} {% block content %}{% include 'webapp/_navbar.html' %}
<div class="cabecera">
  <br>
  <section class="hero is-medium is-transparent is-bold frase fixed">
    <div class="hero-body">
        {% include "webapp/_message.html" %}
      <div class="container">
      {% for q in quote %}
        
      
        <h1 class="title">
          {{q}} 
        </h1>
        
        <h2 class="subtitle">
        </h2>
      {% endfor %}
      </div>
    </div>
  </section>
</div>
<section class="hero is-small is-primary is-bold frase">
  <div class="hero-body">
    <div class="container">
      <h2 class="title center">
        Encuéntrame
      </h2>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <form action="{% url 'animals' %}" method="get">
      <div class="box">
        <div class="column is-half-desktop">
          <div class="content is-medium">
            <p class="subtitle">
              <strong>¿Cómo te gustaría que fuera tu nuevo compañero de viajes?</strong> Selecciona entre algunos de los filtros
              y te mostraremos el que más se adapte a tus necesidades.</p>
          </div>
        </div>
        <div class="contenedor">
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.animal_type name='animal_type' title='Animal' selected=request.GET.animal_type%}
          </div>
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.sex name='sex' title='Sexo' selected=request.GET.sex %}
          </div>
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.size name='size' title='Tamaño' selected=request.GET.size%}
          </div>
          <div class="item">
            {% include 'filter/_filter.html' with field=filter.form.fields.is_puppy name='is_puppy' title='Edad' selected=request.GET.is_puppy%}
          </div>
        </div>
        <div class="center">
          <input type="submit" id="form" value="Lo tengo!" class="button is-primary is-rounded is-medium" />
        </div>
      </div>
    </form>
    <h2 class="title center margin-top">
      Urge adopción o acogida
    </h2>
    <div class="column is-half-desktop">
      <div class="content is-medium">
        <p class="subtitle">Algunos de nuestros amigos
          <strong> necesitan un hogar de foma urgente</strong> debido a problemas de adaptacion o falta espacio en el refugio.</p>
      </div>
    </div>
    <div class="margin-top">
      <div class='columns is-multiline fixed-height'>
        {% for animal in animals %}
        <div class='column is-4-desktop is-half-tablet'>
          <a class="" href="{% url 'animal_detail' slug=animal.slug %}">
            <div class="card">
              <div class="card-image">
                <figure class="image is-4by3">
                  <img src="{{ animal.image.crop.470x350 }}" />
                </figure>
              </div>
              <div class="card-content">
                <div class="media-content">
                  <a class="title is-4" href="{% url 'animal_detail' slug=animal.slug %}">
                    {{animal.name}} {% if animal.state == 'URGENCY' %}
                    <span class="tag is-danger">{{animal.get_state_display}}</span>
                    {% endif %}
                  </a>
                </div>
                <div class="content">
                  <p>{{animal.description|truncatechars_html:175 }}</p>
                </div>
                <div class="columns is-mobile">
                  <div class="column is-half is-half-mobile">
                    <Strong>
                      <label>Mascota:</label>
                    </Strong>
                    {{animal.get_animal_type_display}}
                    <br>
                    <Strong>
                      <label>Sexo:</label>
                    </Strong>
                    {{animal.get_sex_display}}
                    <br>
                    <Strong>
                      <label>Tamaño:</label>
                    </Strong>
                    {{animal.get_size_display}}
                    <br>
                    <br>
                  </div>
                  <div class="column is-half is-half-mobile">
                    <strong>
                      <p>Fecha nacimiento</p>
                    </strong>
                    <time>{{animal.birth_date}}</time>
                  </div>
                </div>
              </div>
            </div>
        </div>
        </a>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<script src="{% static 'js/message.js' %}"></script>
{% endblock content %}